ALTER TABLE medications ADD COLUMN IF NOT EXISTS color TEXT DEFAULT '#3B82F6';
ALTER TABLE health_records ADD COLUMN IF NOT EXISTS color TEXT DEFAULT '#3B82F6';
ALTER TABLE health_records ADD COLUMN IF NOT EXISTS next_appointment_date DATE;
